App.Lesson = DS.Model.extend
  title: DS.attr('string')
  summary: DS.attr('string')
  image: DS.attr('string')
  imageThumbUrl: DS.attr('string')
  imageMediumUrl: DS.attr('string')
  imageLargeUrl: DS.attr('string')
  mp3: DS.attr('string')
  biblebook: DS.belongsTo('App.Biblebook')
  createdAt: DS.attr('date')
