development:
  adapter: postgresql
  database: nateslessons
  username:
  host: localhost

test:
  adapter: postgresql
  database: nateslessons
  username:
  host: localhost

production:
  adapter: postgresql
  database: nateslessons
  username:
