development:
  bucket: natesapp
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
test:
  bucket: natesapp
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
production:
  bucket: natesapp
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
